---
root: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:react-hooks/recommended
  - prettier

settings:
  react:
    version: "17"

  import/core-modules:
    - "@vantage/components"
    - "@vantage/hooks"
    - "@vantage/lib"
    - "@vantage/types"
    - "@vantage/styles"

plugins:
  - import
  - prettier
  - react
  - react-hooks

rules:
  no-bitwise: 0
  react-hooks/exhaustive-deps: 0
  no-return-await: 2
  import/no-unresolved: 2
  import/named: 2
  import/default: 2
  import/export: 2
  react/jsx-uses-react: 0
  react/react-in-jsx-scope: 0

env:
  browser: true
  commonjs: true
  es6: true
  node: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
